name: "Test Docker build"

on:
  pull_request:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker Lint
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile

      - name: Docker Build
        run: docker build -t mqtt-client .
